[package]
name = "bole"
version = "0.2.2"
edition = "2024"
rust-version = "1.89"
authors = ["Glenn Miao (lemorage) <one.lemorage@gmail.com>"]
documentation = "https://docs.rs/bole"
description = "Manage all package managers on your system"
license = "MIT"
readme = "README.md"
repository = "https://github.com/lemorage/bole"
keywords = ["cli", "package-manager", "discovery", "tools"]
categories = ["command-line-utilities", "development-tools"]
include = ["src/**/*", "LICENSE", "README.md", "Cargo.toml"]

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
dashmap = "6.1.0"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.145"
tabled = "0.20.0"
which = "8.0.0"

[dev-dependencies]
tempfile = "3.8.0"

[workspace]
members = ["xtask"]
resolver = "2"
